name: Docs

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  dotnet-version: "5.0.x"
  node-version: "12.x"
  build_version: "0.0.2-alpha.${{ github.run_number }}"

jobs:
  generate-docs:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "3.1.x"
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "2.1.x"
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node-version }}
    - name: Setup psake
      run: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; Install-Module -Name psake
    - name: Build and Deploy packages
      run: Invoke-psake cd
    - name: Install docfx
      run: choco install docfx -y
    - name: Generate docs
      run: docfx ./docs/docfx.json
    - name: Upload docs
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: ./docs/_site
  deploy-docs:
    needs: generate-docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Download docs
      uses: actions/download-artifact@v2
      with:
        name: docs
        path: ./docs/_site
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.PA_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./docs/_site